import React from 'react'
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {

  // TODO: create logic to redirect (logged in) users that don't have permission to an unauthorized page (/unauthorized)

  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
