import React from 'react'
import { Metadata } from 'next'
import { headers as getHeaders } from 'next/dist/server/request/headers'
import config from '@payload-config'
import { getPayload } from 'payload'
import { redirect } from 'next/navigation'

export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const headers = await getHeaders()
  const payloadConfig = await config
  const payload = await getPayload({ config: payloadConfig })
  const { user } = await payload.auth({ headers })

  const roles = user?.roles || []

  const isAuthorized = roles.includes('admin') || roles.includes('dashboard')

  if (!isAuthorized) {
    redirect('/unauthorized')
  }

  return (
    <main>
      {children}
    </main>
  )
}
